### ISSUE TITLE
Additional ID columns

### ISSUE THREAD

**Issue by gregroberts** [fivethirtyeight/russian-troll-tweets#10]
It's been mentioned in some of the other issues here but I think it warrants its own.

First off thanks for releasing this, it's a fantastic dataset. I'm intereested in the network effects going on in these communities, and want to load them into a graph db, but without the tweet ID, retweet ID & account name (as opposed to screen name), I'm not able to connect retweets to tweets, or user mentions to users.

It's possible to get the account name and retweeted status id from the t.co/... url (most redirect to an 'account suspended' page, but you can still see the full url in the request history), but without the (re)tweet ID, you can't connect things up.

**Comment by patrick-lee-warren** [comment]
This is the biggest weakness of the Social Studio data. We do not get the retweet ID, so figuring out who was being retweeted requires laborious text searches and some detective work.

**Comment by gregroberts** [comment]
So not even
