### ISSUE TITLE
Mission regions and shifted columns

### ISSUE THREAD

**Issue by chrisgherbert** [fivethirtyeight/russian-troll-tweets#18]
There are a handful of tweets that are missing a region and have the following columns shifted to the left:

<table>
  <thead>
    <tr>
      <th class="external_author_id-cell">external_author_id</th>
      <th class="author-cell">author</th>
      <th class="content-cell">content</th>
      <th class="region-cell">region</th>
      <th class="language-cell">language</th>
      <th class="publish_date-cell">publish_date</th>
      <th class="harvested_date-cell">harvested_date</th>
      <th class="following-cell">following</th>
      <th class="followers-cell">followers</th>
      <th class="updates-cell">updates</th>
      <th class="post_type-cell">post_type</th>
      <th class="account_type-cell">account_type</th>
      <th class="new_june_2018-cell">new_june_2018</th>
      <th class="retweet-cell">retweet</th>
      <th class="account_category-cell">account_category</th>
      <th class="date_mysql-cell">date_mysql</th>
    </tr>
  </thead>
  <tbody>
    <tr class="firstRow">
      <td class="external_author_id-cell">1670762347</td>
      <td class="author-cell">ADAMCHAPMANJR</td>
      <td class="content-cell">Check out the video I made with @LAEducators to #ThankaLAEducator https://t.co/N7J70kSDsn,United States</td>
      <td class="region-cell">English</td>
      <td class="language-cell">10/6/2016 21:04</td>
      <td class="publish_date-cell">10/6/2016 21:07</td>
      <td class="harvested_date-cell">582</td>
      <td class="following-cell">934</td>
      <td class="followers-cell">1807</td>
      <td class="updates-cell">0</td>
      <td class="post_type-cell">left</td>
      <td class="account_type-cell">0</td>
      <td class="new_june_2018-cell">1</td>
      <td class="retweet-cell">0</td>
      <td class="account_category-cell">NULL</td>
      <td class="date_mysql-cell">2016-10-06 21:07:00</td>
    </tr>
    <tr>
      <td class="external_author_id-cell">1850866398</td>
      <td class="author-cell">BRICEGELLER</td>
      <td class="content-cell">Check out the video I made with @LAEducators to #ThankaLAEducator https://t.co/N7J70kSDsn,United States</td>
      <td class="region-cell">English</td>
      <td class="language-cell">10/6/2016 20:54</td>
      <td class="publish_date-cell">10/6/2016 20:55</td>
      <td class="harvested_date-cell">851</td>
      <td class="following-cell">852</td>
      <td class="followers-cell">1587</td>
      <td class="updates-cell">0</td>
      <td class="post_type-cell">left</td>
      <td class="account_type-cell">0</td>
      <td class="new_june_2018-cell">1</td>
      <td class="retweet-cell">0</td>
      <td class="account_category-cell">NULL</td>
      <td class="date_mysql-cell">2016-10-06 20:55:00</td>
    </tr>
    <tr>
      <td class="external_author_id-cell">1626302035</td>
      <td class="author-cell">CLAYPAIGEBOO</td>
      <td class="content-cell">Check out the video I made with @LAEducators to #ThankaLAEducator https://t.co/N7J70kSDsn,United States</td>
      <td class="region-cell">English</td>
      <td class="language-cell">10/6/2016 20:58</td>
      <td class="publish_date-cell">10/6/2016 20:58</td>
      <td class="harvested_date-cell">776</td>
      <td class="following-cell">916</td>
      <td class="followers-cell">1562</td>
      <td class="updates-cell">0</td>
      <td class="post_type-cell">left</td>
      <td class="account_type-cell">0</td>
      <td class="new_june_2018-cell">1</td>
      <td class="retweet-cell">0</td>
      <td class="account_category-cell">NULL</td>
      <td class="date_mysql-cell">2016-10-06 20:58:00</td>
    </tr>
    <tr>
      <td class="external_author_id-cell">1692501152</td>
      <td class="author-cell">CORNELLBURCHET</td>
      <td class="content-cell">Check out the video I made with @LAEducators to #ThankaLAEducator https://t.co/N7J70kSDsn,United States</td>
      <td class="region-cell">English</td>
      <td class="language-cell">10/6/2016 20:55</td>
      <td class="publish_date-cell">10/6/2016 20:55</td>
      <td class="harvested_date-cell">725</td>
      <td class="following-cell">774</td>
      <td class="followers-cell">1536</td>
      <td class="updates-cell">0</td>
      <td class="post_type-cell">left</td>
      <td class="account_type-cell">0</td>
      <td class="new_june_2018-cell">1</td>
      <td class="retweet-cell">0</td>
      <td class="account_category-cell">NULL</td>
      <td class="date_mysql-cell">2016-10-06 20:55:00</td>
    </tr>
    <tr>
      <td class="external_author_id-cell">2882037326</td>
      <td class="author-cell">DANAGEEZUS</td>
      <td class="content-cell">I need a dance break right meow! (•_•) <) )╯all the single ladies / \  (•_•) \( (> all the single ladies / \  (•_•) <) )╯oh oh oh / ,United States</td>
      <td class="region-cell">English</td>
      <td class="language-cell">7/6/2015 15:03</td>
      <td class="publish_date-cell">7/6/2015 15:03</td>
      <td class="harvested_date-cell">3740</td>
      <td class="following-cell">9351</td>
      <td class="followers-cell">1849</td>
      <td class="updates-cell">NULL</td>
      <td class="post_type-cell">Hashtager</td>
      <td class="account_type-cell">0</td>
      <td class="new_june_2018-cell">0</td>
      <td class="retweet-cell">0</td>
      <td class="account_category-cell">NULL</td>
      <td class="date_mysql-cell">2015-07-06 15:03:00</td>
    </tr>
    <tr class="lastRow">
      <td class="external_author_id-cell">2577152109</td>
      <td class="author-cell">DENN_NIKITIN</td>
      <td class="content-cell">курточка моя так хорошо сидит на ней  \ты пропел эти слова в голове,Unknown</td>
      <td class="region-cell">Russian</td>
      <td class="language-cell">4/15/2017 13:19</td>
      <td class="publish_date-cell">4/15/2017 13:19</td>
      <td class="harvested_date-cell">68</td>
      <td class="following-cell">113</td>
      <td class="followers-cell">6277</td>
      <td class="updates-cell">0</td>
      <td class="post_type-cell">Russian</td>
      <td class="account_type-cell">0</td>
      <td class="new_june_2018-cell">1</td>
      <td class="retweet-cell">0</td>
      <td class="account_category-cell">NULL</td>
      <td class="date_mysql-cell">2017-04-15 13:19:00</td>
    </tr>
  </tbody>
</table>

**Comment by bet4a** [comment]
It looks like something may have gone wrong with CSV parsing? All of these entries **do** have a region (or an `Unknown` region). But in your table, they’re appearing at the end of the `content` columns.

Taking a look at some of these entries on my computer, they seem to share something in common—the final character of the `content` text is a backslash. So it seems your CSV parser is treating `\,` as an escape code for a comma. But the flavor of the CSV used by the dataset doesn’t use backslash escape codes; instead, that combination should be parsed as a textual backslash followed by a `,` column separator.

**Comment by chrisgherbert** [comment]
Ah, thanks.  I'll reimport this and make sure my importer isn't doing that.
