### ISSUE TITLE
Repo appears to be over its data quota and is not allowing downloads

### ISSUE THREAD

**Issue by OliverWS** [fivethirtyeight/russian-troll-tweets#2]
$ git-lfs smudge -- IRAhandle_tweets.csv
Error downloading object: IRAhandle_tweets.csv (80f883c3b641733035cbb7fc0f7068760710dfc647cd69c99f42706cd490b68b)

Smudge error: Error downloading 80f883c3b641733035cbb7fc0f7068760710dfc647cd69c99f42706cd490b68b: batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/: batch response: http: This repository is over its data quota. Purchase more data packs to restore access.
Docs: https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/

**Comment by tlastowka** [comment]
Error message if cloning the whole repository, but same issue

$ git clone https://github.com/fivethirtyeight/russian-troll-tweets/
Cloning into 'russian-troll-tweets'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 22 (delta 7), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.
Downloading IRAhandle_tweets.csv (767 MB)
Error downloading object: IRAhandle_tweets.csv (80f883c): Smudge error: Error downloading IRAhandle_tweets.csv (80f883c3b641733035cbb7fc0f7068760710dfc647cd69c99f42706cd490b68b): batch response: This repository is over its data quota. Purchase more data packs to restore access.



Also, if you are using git for windows and haven't updated in awhile, git lfs isn't built in and you'll get a different error message.  updating to the most recent release will fix that.

**Comment by jaypeedevlin** [comment]
Workaround: https://media.githubusercontent.com/media/fivethirtyeight/russian-troll-tweets/master/IRAhandle_tweets.csv

**Comment by dmil** [comment]
Thank you for your note. We've split up the file into nine smaller files so that it doesn't have to use LFS. You should be able to download it more easily now.

https://github.com/fivethirtyeight/russian-troll-tweets

**Comment by OliverWS** [comment]
Thank you - this is going to be a great resource for research and journalism!
