### ISSUE TITLE
Impossible amounts of followers

### ISSUE THREAD

**Issue by dtspray** [fivethirtyeight/russian-troll-tweets#35]
Did anyone else notice that there are a set of accounts who have more followers than there are users on twitter? Twitter has 336 million users but some of the accounts in the data set have close to 1 billion followers listed. How have you been interpreting this?

Accounts with more than 336 million followers: CHICAGODAILYNEW, DAILYSANFRAN, JENN_ABRAMS, KADIROVRUSSIA, KANSASDAILYNEWS, MAXDEMENTIEV, NEWORLEANSON, NOVOSTIMSK, NOVOSTISPB, ROOMOFRUMOR, SCREAMYMONKEY, SEATTLE_POST, SPECIALAFFAIR, TEN_GOP, TODAYINSYRIA, TODAYNYCITY, TODAYPITTSBURGH, and WASHINGTONLINE.

**Comment by johannessweater** [comment]
Not sure where you're seeing this. Each tweet contains the author's follower count at the time. Could it be that you're adding all of these follower counts together?

**Comment by dtspray** [comment]
> Not sure where you're seeing this. Each tweet contains the author's follower count at the time. Could it be that you're adding all of these follower counts together?

I might be. I will check for it. Thank you!
