### ISSUE TITLE
any plans for improvement? 

### ISSUE THREAD

**Issue by eyejosh** [fivethirtyeight/russian-troll-tweets#8]
Do you plan on improving this? 
the tweets are missing the accounts re-tweeted, they should be prefixed with "RT @usernameRTed".
and the urls tweeted out would nice!

this is an example of a very standard twitter data pull to csv: 
[trump rally search 07.31.2018.xlsx](https://github.com/fivethirtyeight/russian-troll-tweets/files/2247737/trump.rally.search.07.31.2018.xlsx)

thanks!

**Comment by gregroberts** [comment]
+1! Would be really useful to have the tweet ID, the account name & ID if the tweet which was retweeted.

**Comment by johannessweater** [comment]
I'd like to put a vote in for tweet ID. I have a database from the election collected via the streaming API and I'd like to see what I missed -- or if I have additional tweets. 

(Super excited about this data release btw.)

**Comment by John-Brandon** [comment]
Is there a time zone associated with `publish_date` and `harvest_date` (e.g. U.S. Eastern Time)? Thanks for making these data available!

**Comment by patrick-lee-warren** [comment]
The data never had retweet id or account name, and I'm afraid I've botched the tweet id by opening and saving the files in excel, which rounded the integers in the tweet id to 16 digits. I feel like a dummy, but didn't realize there was a fidelity risk there.

**Comment by patrick-lee-warren** [comment]
I just realized how I can do it, I think.  Stand by.
